### ISSUE TITLE
Souligné liens menus

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#101]
Dans le menu, le souligné au survol est discontinu entre le texte et l'icône flèche. C'est pas très joli.

![Capture d’écran 2024-07-26 à 11 09 26](https://github.com/user-attachments/assets/d8d35d56-1b46-4671-86fa-f006c07313b9)

Aussi, le souligné ne se voit pas quand le menu est ouvert, je suppose qu'il est blanc.

**Comment by arnaudlevy** [comment]
@Olivia206 il ne devrait même pas y avoir de soulignement là

**Comment by Olivia206** [comment]
Bonjour @justinpuyo, le souligné n'est en effet pas normal, c'est parce que le thème n'est pas à jour sur le site, je viens de mettre en ligne la dernière version du thème.

Pour ce qui est du souligné des liens intérieurs du menu, je viens d'ouvrir [une PR sur le thème](https://github.com/osunyorg/theme/pull/527).

**Comment by Olivia206** [comment]
Bonjour @justinpuyo, tout est en ordre, c'est bon 🙌
