### ISSUE TITLE
Bug affichage date évènements

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#105]
J'ai un zéro de trop sur l'année des évènements

![Capture d’écran 2024-09-16 à 15 17 50](https://github.com/user-attachments/assets/5c53097a-8718-4d68-9928-2ce8ff0e4e85)
![Capture d’écran 2024-09-16 à 15 22 56](https://github.com/user-attachments/assets/030a90e7-7f55-47fb-b766-8b73b2287991)

**Comment by justinpuyo** [comment]
J'ai l'impression que ça vient du back, mais que sur les évènements récents 

![Capture d’écran 2024-09-16 à 15 25 13](https://github.com/user-attachments/assets/89311a0e-3455-4ad9-b0b8-72b2002da1e2)

**Comment by arnaudlevy** [comment]
@justinpuyo Est-ce que c'est pas juste l'événement qui est en 20024 ? Je veux dire, avec un 0 en trop dans la date au niveau de l'admin ?

**Comment by justinpuyo** [comment]
Effectivement, mea-culpa, j'ai corrigé.

En fait j'avais bien essayé de changer dans l'admin mais il me proposait des années avec un zéro de trop en passant par le calendrier et j'avais l'impression que je pouvais pas éditer à la main.
J'ai certainement mis le zéro de trop en entrant la date à la main quand j'ai crée l'évènement, mais c'est bizarre qu'il accepte une date non conforme, non ?
![Capture d’écran 2024-09-23 à 14 49 50](https://github.com/user-attachments/assets/1907b91d-cabb-432e-8986-07eb356a7c96)

**Comment by arnaudlevy** [comment]
C'est parce qu'elle est conforme, mais dans longtemps !
