### ISSUE TITLE
Retours IUT

### ISSUE THREAD

**Issue by sebousan** [noesya/bordeauxmontaigne-iut#20]
- [x] Passer l'image en 6 / 6 sur la home (réduire d'une col la photo)
- [x] Réduire la hauteur du hero sur la home
- [x] Diminuer la hauteur du footer
- [x] Passer le menu à 4 cols
- [x] Ajouter la signature dans le header 
- [x] Chiffre clés : réduire et 4 cols (tenter 2 en mobile)
- [x] Choisir la couleur prune pour le site-color ? #4C1540
- [x] blocs CTA couleur de la page et texte blanc
- [x] Afficher les images à la une et les chapos
  - [x] Posts
  - [x] Post
  - [x] Pages
  - [x] Page
  - [x] Programs (Justin ne veut pas d'image là)
  - [x] Program
  - [x] Diplomas (Justin ne veut pas d'image là)
  - [x] Diploma (Pas d'image par défaut)
  - [x] Persons 
  - [x] Person
  - [x] Administrators
  - [x] Teachers
  - [x] Authors
- [x] Enlever les filets sur la home (ou clairs ?)
- [x] Ajouter des filets sur les pages (clairs?)

Retours de @arnaudlevy en mobile
- [x] Intégrer le bloc files cf figma
- [x] Finaliser l'intégration du suivant précédent (corps 14, filet plus clairs)
- [x] Finaliser l'intégration du select dans formation (plein largeur, calé sur les marges)
- [x] Le breadcrumb n'est pas scrollable jusqu'à droite

**Comment by alexisben** [comment]
- [ ] Choisir la couleur prune pour le site-color ? #4C1540
- [ ] Réduire la hauteur du hero sur la home (réduire d'une col la photo)
- [ ] Diminuer hauteur header
- [ ] Menu en 4 cols au lieu de 3
