### ISSUE TITLE
Post page aside

### ISSUE THREAD

**Issue by alexisben** [noesya/bordeauxmontaigne-iut#30]
L'aside n'est pas sticky si pas de blocs, du coup 2 comportements différents en fonction du contenu 👍 

Là ça suit : https://www.iut.u-bordeaux-montaigne.fr/actualites/2022/06/23/inscriptions-administratives/

Là ça suit pas : https://www.iut.u-bordeaux-montaigne.fr/actualites/2021/02/24/journee-portes-ouvertes-en-ligne/

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/issues/681
