### ISSUE TITLE
Personnes : Mise à jour non publiée sur "Florence Bord"

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#33]
J'ai modifié plusieurs fois sa fiche, c'est enregistré en back, mais les modifs n'apparaissent pas en front

https://www.iut.u-bordeaux-montaigne.fr/notre-institut/ressources/equipe/florence-bord/

**Comment by SebouChu** [comment]
Je pense que c'est aussi lié à ce problème : https://github.com/noesya/osuny/issues/365

Florence étant enseignante mais liée à aucune formation, sa fiche n'est normalement pas présente sur le site

**Comment by justinpuyo** [comment]
Ok. Par contre j'ai besoin de pouvoir faire apparaitre un enseignant même s'il n'est pas affecté à une formation. C'est rare mais ça peut arriver.
Pour moi, si une personne est cochée "Enseignant" elle doit apparaitre dans l'équipe péda. Il peut y avoir des cas (congé recherche, arrêt longue durée...) où l'enseignant ne donne pas cours actuellement, mais est quand même membre du personnel et doit donc apparaitre quelque part.

**Comment by arnaudlevy** [comment]
@pabois

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/issues/669#issuecomment-1373473318

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/milestone/4
