### ISSUE TITLE
Personnes : sont affichées alors que pas de responsabilité

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#34]
Les personnes qui n'ont aucune case cochée dans "Responsabilités" ne devraient pas apparaitre sur le site.
Je pense que c'est un bug car il me semble que c'était le cas avant.

Cas concernés :
https://www.iut.u-bordeaux-montaigne.fr/notre-institut/ressources/equipe/vincent-bengold/
https://www.iut.u-bordeaux-montaigne.fr/notre-institut/ressources/equipe/aurelie-blot/
https://www.iut.u-bordeaux-montaigne.fr/notre-institut/ressources/equipe/florence-de-mornac/

**Comment by SebouChu** [comment]
C'est lié à ce problème, on travaille dessus ! https://github.com/noesya/osuny/issues/365

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/issues/598
