### ISSUE TITLE
Formations : espace avant le titre "Informations administrative"

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#37]
Il semble qu'il manque de la marge avant le bloc "Informations administratives"
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/carrieres-sociales/animation-sociale-et-socioculturelle/

**Comment by arnaudlevy** [comment]
Tout calé maintenant !
https://aaa--bordeauxmontaigne-iut.netlify.app/formation/offre-de-formation/carrieres-sociales/animation-sociale-et-socioculturelle/
