### ISSUE TITLE
Bloc liste formations : problème d'affichage titres formations

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#39]
Pour les formations qui ont un parent, le titre ne s'affiche pas
Aussi, la liste est un peu imposante intégrée dans une page de texte : peut-être proposer plusieurs layouts dont une plus compacte ?

ex. : https://www.iut.u-bordeaux-montaigne.fr/formation/regimes-dinscriptions/formation-continue/#block-4

**Comment by arnaudlevy** [comment]
Mince, en effet. 
Pb technique + pb graphique (typos trop grosses, il faudrait une taille plus standard)

**Comment by arnaudlevy** [comment]
Je ne comprends pas trop, ce tableau est un tableau classique. Rien n'est automatique (formation avec parent), c'est juste du texte à saisir.

Pour l'option de mise en page, bonne idée !

**Comment by arnaudlevy** [comment]
On a mainteant des paddings en haut et en bas plus petits quand la page n'est pas pleine largeur : 
https://aaa--bordeauxmontaigne-iut.netlify.app/formation/regimes-dinscriptions/formation-continue/#block-11
