### ISSUE TITLE
Bloc fichiers : problème formatages du champ description

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#40]
Dans le champ description du bloc fichiers, les listes sont formatées comme les liens des fichiers.
Merci de remettre le format classique des listes à puces.

ex. "Planning de la formation" : https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/metiers-de-l-animation-sociale-socio-educative-et-socioculturelle/mediation-par-le-jeu-et-gestion-de-ludotheques/#presentation

**Comment by arnaudlevy** [comment]
@alexisben c'est un pb au niveau du front, les données sont ok

**Comment by alexisben** [comment]
Fix dans le thème AAA
