### ISSUE TITLE
Bloc fichiers : taille de la police

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#48]
**Thème AAA**
La taille du titre du fichier est très petite par rapport à celle du format/poids.
J'aurai plutôt vu l'inverse, non ?

https://aaa--bordeauxmontaigne-iut.netlify.app/notre-institut/presentation-de-liut/#block-4

<img width="980" alt="Capture d’écran 2023-01-10 à 16 29 45" src="https://user-images.githubusercontent.com/113047726/211592949-97fb4784-1c20-415e-a947-f32465403ff5.png">

**Comment by justinpuyo** [comment]
C'est mieux, non ?
<img width="992" alt="Capture d’écran 2023-01-10 à 16 31 34" src="https://user-images.githubusercontent.com/113047726/211593518-d99ad43d-3a58-41e9-b426-3fb57ea4d4dc.png">

**Comment by arnaudlevy** [comment]
T'as raison c'est pas normal !
Voilà le figma du thème brut https://www.figma.com/community/file/1176490763864113451

**Comment by arnaudlevy** [comment]
@alexisben c'est une erreur non ?
