### ISSUE TITLE
Formations : limiter le nombre d'actus listées

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#60]
Merci de limiter à 3 ou 4 le nombres d'actus sur les pages formations

**Comment by justinpuyo** [comment]
sinon c'est un peu long
ex : https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/conception-de-projets-et-mediation-artistique-et-culturelle-comedia/

**Comment by alexisben** [comment]
J'ai mis à 4 par défaut, mais on peut maintenant facilement réduire si besoin :)

**Comment by justinpuyo** [comment]
@alexisben 4 ça me semble bien
Merci !
