### ISSUE TITLE
Petites réparations

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/bordeauxmontaigne-iut#64]
## Diplôme
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/bachelor-universitaire-de-technologie/

<img width="1730" alt="image" src="https://user-images.githubusercontent.com/2088968/219132479-de10848b-9642-4933-aae2-ca188f170eed.png">

- [x] Les résumés ne sont pas branchés correctement

<img width="398" alt="image" src="https://user-images.githubusercontent.com/2088968/219133466-4c11f4fd-28d9-4a4a-99a6-fba0301b9070.png">

- [x] Les flèches ne sont pas calées sur la ligne, et semblent très petites

## Offre de formation
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/

<img width="388" alt="image" src="https://user-images.githubusercontent.com/2088968/219139990-9647e3b3-f64b-40ea-897f-d09e30136310.png">

- [x] Les marges sont parties en vrille, cf Figma
- [x] Les flèches aussi :)

## Formation
https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/metiers-du-multimedia-et-de-l-internet/#results

- [x] Dans la TOC, quand on clique sur "Pédagogie", ça ne fait rien. Ca marche sur les enfants mais pas sur les catégories

<img width="390" alt="image" src="https://user-images.githubusercontent.com/2088968/219134749-b5f5e6fe-43fe-4583-aff0-965ea495ec4d.png">

- [x] Les flèches ne sont pas sur la ligne

<img width="402" alt="Capture d’écran 2023-02-15 à 20 39 04" src="https://user-images.githubusercontent.com/2088968/219135075-dba33ce4-beb1-4810-82d4-142bc87c1962.png">

- [x] Il vaudrait mieux que les légendes soient comme ça, en dessous

## Personne

<img width="392" alt="image" src="https://user-images.githubusercontent.com/2088968/219135338-838333cb-5430-4873-a23e-fd3d7afa6dc3.png">

- [x] C'est pas dingue la photo comme ça, il vaudrait mieux que le bleu descende jusqu'à la moitié du cercle

**Comment by arnaudlevy** [comment]
@Olivia206 tu as calé les flèches en bas 
<img width="364" alt="image" src="https://user-images.githubusercontent.com/2088968/221635574-a865a45e-c3b4-41bc-8007-877ddd93c91e.png">

C'est joli, mais... on ne peut pas cliquer sur le résumé donc on dirait que ça marche pas.
Soit on respecte la maquette et on aligne la flèche sur le titre cliquable, soit on étend la zone sensible à toute la carte

**Comment by Olivia206** [comment]
Pour l'instant j'ai suivi la maquette, mais est-ce que tu préfères que toute la zone soit cliquable ?

**Comment by arnaudlevy** [comment]
Oui stp :)

**Comment by Olivia206** [comment]
C'est fait !

**Comment by arnaudlevy** [comment]
Cool ! Et la photo, le dernier point ?

**Comment by Olivia206** [comment]
C'était réglé !

**Comment by arnaudlevy** [comment]
Bravo !
