### ISSUE TITLE
Bloc chapitre : mauvaise couleur

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#65]
Le bloc chapitre avec mise en forme "Forte mise en avant" devrait être vert sur les pages formations et non prune.

ex. : https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/animation-sociale-et-socioculturelle/#block-2

**Comment by justinpuyo** [comment]
Pareil sur les pages standards : devrait être bleu et non prune

**Comment by arnaudlevy** [comment]
@Olivia206 @alexisben vous avez traité ?

**Comment by alexisben** [comment]
m'en occupe
