### ISSUE TITLE
Index diplômes : bloc fichiers non fonctionnel

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#70]
Sur la page diplôme du [BUT](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/bachelor-universitaire-de-technologie/), je ne peux plus publier de fichiers.
Je n'ai pas de problème en back mais le fichier n'apparaît pas en front.
Cela fonctionne toujours sur les pages classiques.

**Comment by alexisben** [comment]
Mh j'ai l'impression que le fichier en question ne passe pas, pas encore trouvé pourquoi. On investigue !

**Comment by justinpuyo** [comment]
@alexisben  J'ai mis le même fichier [ici](https://www.iut.u-bordeaux-montaigne.fr/tests/#block-3) et ça passe.
Quand je mets un autre fichier sur [BUT](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/bachelor-universitaire-de-technologie/), ça passe pas. Ni sur [LP](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/diplomes/licence-professionnelle/)
Je pense pas que ça soit le fichier qui pose problème

**Comment by alexisben** [comment]
@justinpuyo oui tu as raison, il semblerait que ça coince quand on ajoute un fichier à un diplôme. @pabois @SebouChu @arnaudlevy

**Comment by arnaudlevy** [comment]
Oui on va régler le pb dans le refactor des dépendances

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/pull/833
