### ISSUE TITLE
Bloc chapitre, mise en avant : position de l'image

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#71]
En version desktop il manque des marges pour l'image avec la mise en page "mise en avant"
Sur version mobile c'est ok
ex. : https://www.iut.u-bordeaux-montaigne.fr/actualites/2022-12-13-portes-ouvertes-et-salons-2023/#block-2

**Comment by alexisben** [comment]
@arnaudlevy tu veux gérer comment ? 

Sachant que design thème : 

<img width="739" alt="image" src="https://user-images.githubusercontent.com/4630530/222375030-ea08a882-d5e7-45b7-9b1a-af6078c71deb.png">

**Comment by justinpuyo** [comment]
@alexisben @arnaudlevy désolé j'ai pas vérifié le design :-/
Du coup ça peux rester comme ça. C'est parce que j'ai utilisé un picto que ça fait bizarre, du coup c'est à moi de mettre des marges dans mon image.
