### ISSUE TITLE
Problème résolution images CTA

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#74]
J'ai l'impression qu'il y a un soucis avec le choix de la taille des images du bloc CTA.
C'est très flagrant en mode pleine largeur desktop et mobile.
https://www.iut.u-bordeaux-montaigne.fr/

![Capture d’écran 2023-07-06 à 09 59 22](https://github.com/noesya/bordeauxmontaigne-iut/assets/113047726/5809918a-ae72-4f65-a6a9-5eccd0c65986)
![Capture d’écran 2023-07-06 à 10 02 13](https://github.com/noesya/bordeauxmontaigne-iut/assets/113047726/868e806b-63b5-4c06-ba21-66c2feda1bce)

La même photo sur une page ça passe nickel :
https://www.iut.u-bordeaux-montaigne.fr/formation/scolarite/la-rentree-universitaire/

![Capture d’écran 2023-07-06 à 10 06 23](https://github.com/noesya/bordeauxmontaigne-iut/assets/113047726/c851628a-2081-425e-a6c6-314271dc8acc)

**Comment by alexisben** [comment]
Hello @justinpuyo ! Bien vu ! c'est réparé :)
