### ISSUE TITLE
Pages formations : trop d'espace entre les blocs

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#80]
J'ai beaucoup trop de "vide" sur les pages formations
J'aime bien les design aérés, mais là c'est carrément un gros courant d'air 😂

[https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/metiers-du-livre-et-du-patrimoine/#admission](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/metiers-du-livre-et-du-patrimoine/#admission)

**Comment by arnaudlevy** [comment]
ha ha ha oui c'est un effet de bord de cette PR https://github.com/noesya/osuny/pull/1344

@pabois est dessus !

**Comment by pabois** [comment]
@justinpuyo c'est bon normalement !
