### ISSUE TITLE
Problème pour dépublier "Organisations"

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#85]
Je fais des tests sur les organisations depuis hier et j'ai repéré un bug.
Lorsque je dépublie la page Organisations elle reste en ligne mais devient [Organizations](https://www.iut.u-bordeaux-montaigne.fr/organizations/) (avec un Z)

Vous pouvez faire des tests dessus si besoin. Pour le moment je ne l'utilise pas, elle est accessible uniquement via le plan du site.

**Comment by pabois** [comment]
lié à #86, c'est le même problème.
Hugo créé par défaut des index. nous on les écrase avec certains types de contenus (par exemple notre page organisations). Mais si tu les désactives il revient sur l'index par défaut. Et toutes les pages ne sont pas écrasées (par exemple celle de #86)

**Comment by justinpuyo** [comment]
Ok, pour "Organisations" je la laisse publiée du coup, ça me va comme ça
