### ISSUE TITLE
Index Pages vide

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#86]
La page index [Pages](https://www.iut.u-bordeaux-montaigne.fr/pages/), que l'on trouve via le plan du site, est vide.
Il faudrait avoir par défaut la liste des pages. Si possible avec l'arborescence.

**Comment by pabois** [comment]
lié à #85

**Comment by justinpuyo** [comment]
Par contre, contrairement à "Organisations" je n'ai pas de page "Pages" dans le back, donc je n'ai aucun moyen de la personnaliser.

**Comment by pabois** [comment]
Oui comme je tentais de l'expliquer dans l'issue 85 tu n'as pas toujours d'overwrite, du coup certaines pages sont TOUJOURS générées par Hugo actuellement.
Il faut qu'on trouve une solution.

**Comment by arnaudlevy** [comment]
https://gohugo.io/content-management/build-options/#readout
