### ISSUE TITLE
Fil d'ariane trop gros

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#94]
Sur la page [Offre de formation](https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/), le fil d'ariane est plus gros que d'habitude.
Je ne l'ai pas constaté sur d'autres pages.

**Comment by arnaudlevy** [comment]
![Capture d’écran 2024-04-03 à 09 57 13](https://github.com/osunyorg/bordeauxmontaigne-iut/assets/2088968/1aa61320-06d9-45dc-a2e7-bfbe6d08f594)
