### ISSUE TITLE
Actu des formations : retour à la mise en forme d'avant

### ISSUE THREAD

**Issue by justinpuyo** [noesya/bordeauxmontaigne-iut#97]
Depuis une récente maj la liste des actu sur les pages formations n'affiche que les titres : https://www.iut.u-bordeaux-montaigne.fr/formation/offre-de-formation/metiers-du-livre-et-du-patrimoine/#actualites

J'aimerai retrouver la version d'avant qui correspondait à la mise en forme Liste du bloc Actualités.

**Comment by arnaudlevy** [comment]
@Olivia206 tu peux prendre stp ?

**Comment by Olivia206** [comment]
Yes je m'en occupe

**Comment by Olivia206** [comment]
@justinpuyo c'est en ligne !
